default:
  image: maven:3.9.15-amazoncorretto-11

stages:
  - pre-build
  - build

download-javafx:
  stage: pre-build
  script:
    - apt-get update -y
    - apt-get install -y openjfx
  artifacts:
    paths:
      - build/

build-front:
  stage: build
  script:
    - cd project-integration
    - 'mvn clean package'
