stages:
  - build

build-front:
  stage: build
  tags:
    - local_runner
  script:
    - cd project-integration
    - 'mvn clean package'
  artifacts:
    paths:
      - project-integration/target/jfx/native/*.exe
